### ISSUE TITLE
网关里获取routes一直是空呢

### ISSUE THREAD

**Issue by ligg** [grissomlau/jimu#15]
网关里获取routes一直是空呢

**Comment by grissomlau** [comment]
能详细一点？

**Comment by ligg** [comment]
var serviceDiscovery = JimuClient.Host.Container.Resolve<IClientServiceDiscovery>();
            var routes = await serviceDiscovery.GetRoutesAsync();
这里获取到的永远空是空，断点监视routes变量的时候，task每次是能够正确获取到所有的routes信息并写到concurrentqueue里的，但是controller里只要一获取routes就变成空了

**Comment by grissomlau** [comment]
@ligg 
没遇到这问题

![image](https://user-images.githubusercontent.com/4479670/69949104-cddfe180-152b-11ea-9786-8a1da8c96991.png)
