### ISSUE TITLE
apigateway 能支撑高可用吗

### ISSUE THREAD

**Issue by dgc1** [grissomlau/jimu#16]
挺轻挺好的一个架构，准备用于一个分布式嵌入式系统，但不知道 apigateway支撑部署apigateway集群以达到高可用的目的吗

**Comment by grissomlau** [comment]
可以的，用 nginx -> apigateway（一个或多个）-> server 进行集群

**Comment by dgc1** [comment]
> 可以的，用 nginx -> apigateway（一个或多个）-> server 进行集群

microServer 是分别连接到apigateway下吗，我的理解架构如下，请问描述是否有误：
![1](https://user-images.githubusercontent.com/20265213/69937205-0e803080-1515-11ea-9582-0152a578f1b5.png)

**Comment by grissomlau** [comment]
@liuguijunhao 
如何需要网关集群（提高网关可用性），可以这么弄。
如果仅仅需要微服务进行集群，Apigateway 已经支持负载均衡（轮训），可以一个 apigateway 对多个微服务，比喻你要对 News 进行集群，可以 1 apigateway - * news;

**Comment by dgc1** [comment]
可能我的图描述不太清楚，我们的运行环境是嵌入式单板，因为业场景设计，每块单板都有离线挂掉的可能性(同一时间不考虑多块同时离线)，如果只有一个Apigateway并且刚好它离线了，那对外的服务就变成不可访问了。
所以我理解【nginx -> apigateway（一个或多个）-> server】模式中nginx可以是集群，microServer可以有多个甚至主备，discoveryServer也可以是集群，不清楚多个apigateway和其他模块间的关系.
另外，这种模式下，discoveryServer里面的资源被多个 apigateway复用，那同一个microServer会被多个apigateway调用吧，我理解有问题吗？

**Comment by grissomlau** [comment]
@liuguijunhao 没错，就是这样。

**Comment by dgc1** [comment]
好的，谢谢 @grissomlau
