### ISSUE TITLE
关于Sample是中HelloResponse

### ISSUE THREAD

**Issue by ZhengJian1996** [grissomlau/jimu#22]
请问两个文件HelloResponse和HelloRequest您是不是忘了上传了

**Comment by dalangtk** [comment]
我在IService.User的dto中加了这几个类就好了
public class HelloRequest : IJimuRequest
    {
        public string Greeting { get; set; }

        public string QueueName => "HelloRequest";
    }
    public class HelloResponse
    {
        public string Greeting { get; set; }
    }
    public class UserAdded: IJimuEvent
    {
        public string UserName { get; set; }
    }

**Comment by ZhengJian1996** [comment]
> 我在IService.User的dto中加了这几个类就好了
> public class HelloRequest : IJimuRequest
> {
> public string Greeting { get; set; }
> 
> ```
>     public string QueueName => "HelloRequest";
> }
> public class HelloResponse
> {
>     public string Greeting { get; set; }
> }
> public class UserAdded: IJimuEvent
> {
>     public string UserName { get; set; }
> }
> ```

感谢
